"""Generate SkyMetric Problem Statement & Solution PDF document."""

from fpdf import FPDF


class SkyMetricPDF(FPDF):
    def header(self):
        if self.page_no() > 1:
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(128, 128, 128)
            self.cell(0, 8, "SkyMetric - India Airfare Price Index System", align="L")
            self.cell(0, 8, f"Page {self.page_no()}", align="R", new_x="LMARGIN", new_y="NEXT")
            self.set_draw_color(200, 200, 200)
            self.line(10, 18, 200, 18)
            self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(160, 160, 160)
        self.cell(0, 10, "Generated by SkyMetric System | github.com/skymetric", align="C")

    def section_title(self, title):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(30, 30, 30)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(59, 130, 246)
        self.set_line_width(0.8)
        self.line(10, self.get_y(), 70, self.get_y())
        self.set_line_width(0.2)
        self.ln(6)

    def sub_title(self, title):
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(50, 50, 50)
        self.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def body_text(self, text):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(60, 60, 60)
        self.multi_cell(0, 5.5, text)
        self.ln(3)

    def bullet(self, text, indent=15):
        x = self.get_x()
        self.set_font("Helvetica", "", 10)
        self.set_text_color(60, 60, 60)
        self.set_x(x + indent)
        self.cell(4, 5.5, "-")
        self.multi_cell(0, 5.5, text, new_x="LMARGIN")
        self.ln(1.5)

    def numbered_item(self, num, text, indent=15):
        x = self.get_x()
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(59, 130, 246)
        self.set_x(x + indent)
        self.cell(8, 5.5, f"{num}.")
        self.set_font("Helvetica", "", 10)
        self.set_text_color(60, 60, 60)
        self.multi_cell(0, 5.5, text, new_x="LMARGIN")
        self.ln(2)

    def table_header(self, cols, widths):
        self.set_font("Helvetica", "B", 9)
        self.set_fill_color(240, 240, 245)
        self.set_text_color(30, 30, 30)
        for i, col in enumerate(cols):
            self.cell(widths[i], 7, col, border=1, fill=True, align="C")
        self.ln()

    def table_row(self, cells, widths, fill=False):
        self.set_font("Helvetica", "", 9)
        self.set_text_color(50, 50, 50)
        if fill:
            self.set_fill_color(248, 248, 252)
        for i, cell in enumerate(cells):
            align = "L" if i == 0 else "C"
            self.cell(widths[i], 6.5, str(cell), border=1, fill=fill, align=align)
        self.ln()


def generate_pdf():
    pdf = SkyMetricPDF()
    pdf.set_auto_page_break(auto=True, margin=20)

    # ── PAGE 1: Title ──
    pdf.add_page()
    pdf.ln(40)
    pdf.set_font("Helvetica", "B", 32)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 15, "SkyMetric", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 16)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 10, "India Airfare Price Index System", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)
    pdf.set_draw_color(59, 130, 246)
    pdf.set_line_width(1.2)
    pdf.line(60, pdf.get_y(), 150, pdf.get_y())
    pdf.set_line_width(0.2)
    pdf.ln(12)
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, "Problem Statement & Proposed Solution", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 11)
    pdf.cell(0, 8, "Real-Time DGCA Passenger-Weighted Airfare Index", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(30)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 7, "Tech Stack: Python 3.14 | FastAPI | Playwright | Next.js 16 | Shadcn UI | Recharts", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, "Database: SQLite + SQLAlchemy ORM", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, "Index Formulas: Jevons | Laspeyres | Chain-Laspeyres", align="C", new_x="LMARGIN", new_y="NEXT")

    # ── PAGE 2: Problem Statement ──
    pdf.add_page()
    pdf.section_title("1. Problem Statement")

    pdf.sub_title("Background")
    pdf.body_text(
        "India is the third-largest domestic aviation market in the world, with over 150 million "
        "passengers flying annually (DGCA 2023-24). Despite this scale, there is no publicly "
        "available, standardized, real-time airfare price index for the Indian market."
    )

    pdf.sub_title("Core Problems Identified")

    pdf.numbered_item(1,
        "No Centralized Fare Index: The Directorate General of Civil Aviation (DGCA) publishes "
        "passenger volume statistics and airline performance data, but does not compute or "
        "publish a fare price index. Passengers and analysts lack a benchmark to understand "
        "whether airfares are rising, falling, or stable."
    )
    pdf.numbered_item(2,
        "Opaque Pricing by OTAs: Online Travel Agencies (MakeMyTrip, Yatra, EaseMyTrip) and "
        "airline websites (IndiGo, Air India) display point-in-time fares with no historical "
        "context. A passenger booking a DEL-BOM ticket for Rs.5,200 has no way to know if this "
        "is above or below the market average for that corridor."
    )
    pdf.numbered_item(3,
        "No Advance-Purchase Analysis: Airline pricing is heavily influenced by booking lead "
        "time (how far in advance the ticket is purchased). There is no public tool that "
        "quantifies the price elasticity across booking windows (T+1 vs T+7 vs T+30 vs T+45)."
    )
    pdf.numbered_item(4,
        "Missing Sector-Level Granularity: National-level inflation indices (CPI, WPI) do not "
        "capture corridor-specific fare dynamics. The DEL-IXS (Silchar) route behaves very "
        "differently from DEL-BOM (Mumbai), but both are treated identically in aggregate data."
    )
    pdf.numbered_item(5,
        "No Carrier Comparison Framework: Passengers cannot easily compare fare levels across "
        "carriers on the same route. Market share data exists (IndiGo at 63.6%) but fare "
        "competitiveness data is not publicly available."
    )
    pdf.numbered_item(6,
        "No Structured Data for Policymakers: Organizations like MoSPI, RBI, and NSO need "
        "structured airfare data for inflation modeling and monetary policy decisions. Currently, "
        "no API or dataset provides this in a machine-readable format."
    )

    pdf.sub_title("Impact")
    pdf.body_text(
        "The absence of a fare index leads to: (a) passengers overpaying due to lack of price "
        "discovery, (b) airlines unable to benchmark against competitors, (c) policymakers "
        "making inflation estimates without real airfare data, and (d) researchers lacking a "
        "reliable dataset for aviation economics studies."
    )

    # ── PAGE 3: Proposed Solution ──
    pdf.add_page()
    pdf.section_title("2. Proposed Solution: SkyMetric")

    pdf.body_text(
        "SkyMetric (SkyMetric Airfare Index for India) is an end-to-end system that scrapes real-time "
        "fare data from multiple airline and OTA sources, computes a DGCA Passenger-Weighted "
        "Basket Index, and presents it through a modern web dashboard with interactive "
        "visualizations."
    )

    pdf.sub_title("System Architecture")
    pdf.set_font("Courier", "", 9)
    pdf.set_text_color(50, 50, 50)

    arch_lines = [
        "+------------------+    +------------------+    +------------------+",
        "|   SCRAPER LAYER  |    |  PIPELINE LAYER  |    |  INDEX ENGINE    |",
        "|                  |    |                  |    |                  |",
        "|  Playwright      |--->|  Normalize       |--->|  Jevons Index    |",
        "|  (7 OTA Sources) |    |  Validate        |    |  Laspeyres Index |",
        "|  Stealth Mode    |    |  Deduplicate     |    |  Chain-Laspeyres |",
        "|  Rate Limiting   |    |  Outlier Removal |    |  DGCA Weighting  |",
        "+------------------+    +------------------+    +------------------+",
        "         |                                               |",
        "         v                                               v",
        "+------------------+                           +------------------+",
        "|  SQLite Database |<--------------------------|  FastAPI REST    |",
        "|  fares table     |                           |  6 API Endpoints |",
        "+------------------+                           +------------------+",
        "                                                       |",
        "                                                       v",
        "                                               +------------------+",
        "                                               |  Next.js Dashboard|",
        "                                               |  5 Interactive   |",
        "                                               |  Pages           |",
        "                                               +------------------+",
    ]
    for line in arch_lines:
        pdf.cell(0, 4.2, line, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    pdf.set_font("Helvetica", "", 10)
    pdf.sub_title("Key Design Decisions")
    pdf.bullet("DGCA Passenger-Weighted Basket: Corridor weights are derived from DGCA city-pair passenger traffic statistics (2023-24), ensuring the index reflects actual passenger distribution.")
    pdf.bullet("10 Monitored Corridors: 8 Metro Trunk routes (DEL-BOM, DEL-BLR, BOM-BLR, etc.) + 2 Regional Thin routes (DEL-IXS, DEL-DHM) covering ~90% of domestic passenger traffic.")
    pdf.bullet("6 Carriers Tracked: IndiGo (63.6%), Air India (15.2%), Vistara (9.1%), SpiceJet (5.5%), Akasa Air (4.1%), Air India Express (2.5%).")
    pdf.bullet("5 Advance-Purchase Windows: T+1 (Emergency), T+7 (Short-Horizon), T+15 (Anchor), T+30 (Baseline), T+45 (Early Bird) to capture booking lead-time elasticity.")
    pdf.bullet("Real-Time Scraping: Playwright headless browser with stealth mode, random user agents, rate limiting (2-3s delays), and exponential backoff for reliability.")

    # ── PAGE 4: Index Methodology ──
    pdf.add_page()
    pdf.section_title("3. Index Methodology")

    pdf.sub_title("Jevons Index (Elementary)")
    pdf.body_text(
        "The Jevons index is the geometric mean of price relatives. It is used as the elementary "
        "index when no explicit quantity weights are available."
    )
    pdf.set_font("Courier", "", 10)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 6, "  I = (product(p_t / p_t0))^(1/n) * 100", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    pdf.sub_title("Laspeyres Index (Weighted)")
    pdf.body_text(
        "The Laspeyres index uses DGCA passenger weights to compute a weighted arithmetic mean "
        "of price relatives across corridors."
    )
    pdf.set_font("Courier", "", 10)
    pdf.cell(0, 6, "  I = (sum(w_i * p_ti / p_t0i) / sum(w_i)) * 100", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    pdf.sub_title("Chain-Laspeyres (Rolling)")
    pdf.body_text(
        "The Chain-Laspeyres index links period-to-period indices multiplicatively, allowing "
        "the basket composition to change over time."
    )
    pdf.set_font("Courier", "", 10)
    pdf.cell(0, 6, "  I_chain = 100 * product(link_i / 100)", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    pdf.set_font("Helvetica", "", 10)
    pdf.sub_title("National Index Computation")
    pdf.body_text(
        "The national SkyMetric headline index is computed at the T+15 advance window (the anchor "
        "window). Sector indices for each corridor are computed using the Jevons formula, then "
        "aggregated using DGCA passenger-weighted averages to produce the national index. "
        "Base value is set to 100.00."
    )
    pdf.body_text(
        "The system also computes sub-indices for all 5 advance windows (T+1, T+7, T+15, T+30, "
        "T+45), allowing users to see how the index varies by booking lead time."
    )

    pdf.sub_title("Data Cleaning Pipeline")
    pdf.numbered_item(1, "Validation: Require origin, destination, carrier, and total_fare > 0.")
    pdf.numbered_item(2, "Normalization: Standardize IATA codes, recompute fares, fill defaults.")
    pdf.numbered_item(3, "Deduplication: Remove cross-platform duplicates, keeping latest timestamp.")
    pdf.numbered_item(4, "Outlier Removal: Z-score threshold of 3.0 to filter anomalous fares.")

    # ── PAGE 5: Dashboard Features ──
    pdf.add_page()
    pdf.section_title("4. Dashboard Features")

    pdf.sub_title("Page 1: National Airfare Price Index (Home)")
    pdf.bullet("KPI Cards: Headline index, 24h change (%), monitored corridors count, pipeline status.")
    pdf.bullet("30-Day Line Chart: National price index trend with Base=100 reference line.")
    pdf.bullet("Advance Booking Sub-Indices: T+1 to T+45 cards showing per-window index values.")
    pdf.bullet("Corridor Index Breakdown: Table of 10 corridors with index, change %, classification.")
    pdf.bullet("Fare Breakdown Donut: Average fare composition (base fare, taxes, convenience, UDF).")
    pdf.bullet("Day-of-Week Heatmap: Which days are cheapest vs most expensive per corridor.")
    pdf.bullet("Scraper Status Dashboard: Run scraper, view quotes collected, sources checked.")

    pdf.sub_title("Page 2: Route Heatmap")
    pdf.bullet("Sector x Date fare matrix for 10 corridors over 30 days.")
    pdf.bullet("Origin/Destination city filter dropdowns.")
    pdf.bullet("Color-coded cells: Emerald (Low) -> Yellow (Medium) -> Orange (High) -> Red (Peak).")
    pdf.bullet("Row averages and summary stats: Lowest, Highest, Average Fare, Fare Spread (%).")
    pdf.bullet("Interactive tooltips with exact fare values on hover.")

    pdf.sub_title("Page 3: Advance Purchase Elasticity")
    pdf.bullet("Multi-line chart showing lead-time price curves per corridor.")
    pdf.bullet("X-axis: T+1 to T+45 advance windows. Y-axis: Average fare in INR.")
    pdf.bullet("5 summary cards: Emergency (T+1), Short-Horizon (T+7), Anchor (T+15), Baseline (T+30), Early Bird (T+45).")

    pdf.sub_title("Page 4: Carrier Analysis")
    pdf.bullet("Market Share Distribution: Horizontal bar chart for 6 carriers.")
    pdf.bullet("Average Base Fare: Vertical bar chart comparing carrier pricing.")
    pdf.bullet("Carrier Detail Table: Market share, avg fare, taxes (18%), total estimated fare.")

    pdf.sub_title("Page 5: API Explorer")
    pdf.bullet("Embedded FastAPI Swagger UI for interactive API testing.")
    pdf.bullet("Reference grid of 6 GET endpoints for programmatic access.")

    # ── PAGE 6: Tech Stack + Future Scope ──
    pdf.add_page()
    pdf.section_title("5. Technical Stack")

    pdf.sub_title("Backend")
    cols = ["Component", "Technology", "Purpose"]
    widths = [45, 55, 90]
    pdf.table_header(cols, widths)
    rows = [
        ("Language", "Python 3.14", "Core application logic"),
        ("Web Framework", "FastAPI", "REST API with async support"),
        ("Database", "SQLite + SQLAlchemy", "Fare storage and querying"),
        ("Scraper", "Playwright", "Headless browser automation"),
        ("Data Validation", "Pydantic Settings", "Configuration management"),
        ("Testing", "pytest (45/45 passing)", "Unit and integration tests"),
    ]
    for i, row in enumerate(rows):
        pdf.table_row(row, widths, fill=(i % 2 == 0))

    pdf.ln(6)
    pdf.sub_title("Frontend")
    pdf.table_header(cols, widths)
    rows = [
        ("Framework", "Next.js 16.3.4", "React SSR/SSG with Turbopack"),
        ("Language", "TypeScript", "Type-safe development"),
        ("UI Library", "Shadcn UI + Tailwind CSS", "Modern component system"),
        ("Charts", "Recharts", "Interactive data visualizations"),
        ("State", "TanStack Query", "Server state caching/polling"),
        ("Icons", "Lucide React", "Consistent icon system"),
    ]
    for i, row in enumerate(rows):
        pdf.table_row(row, widths, fill=(i % 2 == 0))

    pdf.ln(10)
    pdf.section_title("6. Future Scope")
    pdf.bullet("Real-Time Streaming: Replace periodic scraping with WebSocket-based live fare feeds.")
    pdf.bullet("Airline API Integration: Direct API access to IndiGo, Air India for structured data.")
    pdf.bullet("ML Price Forecasting: LSTM/Transformer models for fare prediction at T-7, T-15, T-30.")
    pdf.bullet("Consumer Alerts: Push notifications when fares drop below user-defined thresholds.")
    pdf.bullet("International Expansion: Extend to SAARC and ASEAN corridors.")
    pdf.bullet("MoSPI/RBI Integration: Official API for inflation modeling and monetary policy.")
    pdf.bullet("Mobile App: React Native companion for on-the-go fare tracking.")
    pdf.bullet("Historical Database: Build a multi-year fare archive for trend analysis.")

    # ── Save ──
    output_path = r"C:\Users\prath\OneDrive\Desktop\videos\SkyMetric_Problem_Statement.pdf"
    pdf.output(output_path)
    print(f"PDF generated: {output_path}")


if __name__ == "__main__":
    generate_pdf()
